version: '2'
services:
  scrabbledb2-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/scrabbledb2/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=scrabbledb2
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
